name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - name: Install prerequisites
        run: |
          sudo apt update -y
          curl -fsSL https://fvm.app/install.sh | bash
          echo "/home/runner/fvm/bin:$PATH" >> $GITHUB_PATH
      - name: Run tests
        run: |
          fvm flutter pub get
          fvm dart run build_runner build --delete-conflicting-outputs
          fvm flutter test
